tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'thoughtbot/formulae'
tap 'neovim/neovim'

brew 'rcm'
brew 'zsh'
brew 'vim', args: ['override-system-vi']
brew 'neovim', args: ['HEAD']
brew 'reattach-to-user-namespace'
brew 'ack'
brew 'git'
brew 'imagemagick'
brew 'node'
brew 'tmux'
brew 'thefuck'
brew 'postgresql'
brew 'rbenv'
brew 'ruby-build'
brew 'hub'
brew 'wget'
brew 'ctags'
brew 'direnv'
brew 'ngrok'
brew 'awscli'
brew 'awsebcli'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'graphviz'

cask 'virtualbox'
cask 'google-chrome'
cask 'firefox'
cask 'dropbox'
cask 'iterm2'
cask 'skype'
cask 'slate'
cask 'spotify'
cask 'transmission'
cask 'rowanj-gitx'
cask 'istat-menus'
cask 'sonos'
cask 'alfred'
